apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: frontend-app
  name: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer



---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: frontend-app
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: redrighthand172/nextjs:2d5534c91ec22851dd0851290dc45b9905cafbfe
        ports:
        - containerPort: 3000
