name: Build, Push Docker Image, and Update Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            redrighthand172/nextjs:latest
            redrighthand172/nextjs:${{ github.sha }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-docker

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Update Image Tag in Kubernetes Manifest
      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: redrighthand172/nextjs:.*|image: redrighthand172/nextjs:latest|" ./k9s/service.yaml
          git config user.name "rajeevdhaka"
          git config user.email "rajeevdhaka.work@gmail.com"
          git add ./k9s/service.yaml
          git commit -m "Update image tag to latest"
          git push origin main